### ISSUE TITLE
Support credential re-generation

### ISSUE THREAD

**Issue by scottfrederick** [spring-projects/spring-credhub#13]
http://credhub-api.cfapps.io/#regenerate-credentials

**Comment by pivotal-danjahner** [comment]
Heads up - We've updated the regenerate endpoint to use the endpoint `api/v1/regenerate` in server versions 1.4.0+. We will maintain regenerate at `api/v1/data` for a few releases, so you can choose whichever makes sense, depending on what versions of CredHub server you want it to support.
