### ISSUE TITLE
NullPointerException when adding permission.

### ISSUE THREAD

**Issue by Zee-Khan** [spring-projects/spring-credhub#32]
When POSTing to PERMISSIONS_URL_PATH = "/api/v1/permissions", no body is returned as it is a void function [setAccessControlEntries](https://github.com/cloudfoundry-incubator/credhub/blob/8e84af7bc6c3ff2d59a88394d700fbc729c331e6/src/main/java/org/cloudfoundry/credhub/controller/v1/PermissionsController.java#L48)

In the spring-credhub adapter, it attempts to get permissions from within the null body. [addPermission](https://github.com/spring-projects/spring-credhub/blob/13f0f734fad64a534573a711af84d662e05741c2/spring-credhub-core/src/main/java/org/springframework/credhub/core/CredHubTemplate.java#L312)

The v2 of this function does return a body of permissions, but this release is still using v1.

**Comment by scottfrederick** [comment]
Fixed via #33
