### ISSUE TITLE
GetServiceInstanceBindingRequest is missing optional query string parameters

### ISSUE THREAD

**Issue by Zavael** [spring-projects/spring-credhub#72]
As [Open Service Broker specification](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#parameters-7) defines getting (fetching) a service binding

> The request provides these query string parameters as useful hints for brokers.
> | Query-String Field | Type | Description |
> -- | -- | --
> service_id | string | ID of the Service Offering from the catalog. If present, MUST be a non-empty string.
> plan_id | string | ID of the Service Plan from the catalog. If present, MUST be a non-empty string.

Currently the spring implementation does not support this. Could you please suport them? When using credhub as credential storage, broker needs the `serviceOfferingName` to create the `ServiceInstanceCredentialName` and it would be helpful to retrieve it from catalog when this parameters would be included in request.

**Comment by scottfrederick** [comment]
@Zavael This issue appears to be misplaced, as providing parameters to service brokers is the responsibility of the [Spring Cloud Open Service Broker](https://spring.io/projects/spring-cloud-open-service-broker) project, not Spring CredHub. It looks like the issue has [already been raised](https://github.com/spring-cloud/spring-cloud-open-service-broker/issues/287) in Spring Cloud Open Service Broker, and a fix is planned for a future release. If you don't think that issue addresses your needs, please open a new issue in that project. 

I'll close this issue in favor of the Spring Cloud OSB issue. Feel free to re-open it with more information if you think there's something else Spring CredHub needs to do.

**Comment by Zavael** [comment]
@scottfrederick Oh my... You are right, thank you for directing me!
